secret:
  # Type of secret of your API key
  # One of: "HMAC" | "RSA"
  type: RSA
  api_key_file: ./secrets/api.key
  private_key_file: ./secrets/key.pem

  # Saves sub account's API keys.
  store:
    enabled: true
    path: ./secrets/store.json

coins:
  - BTC
  - SOL

# Transfer all balances to `transfer.to` from `transfer.from` before execution.
# Trade is made as an account specified at `transfer.to`.
# Use username to specify an account.
# "$MAIN" is special word that indicates main account.
transfer:
  enabled: true
  to:
    - username: $MAIN # Username that act trading.
  from:
    - nickname: foo # Display name. It does not need to be same as sub account's nickname in Bybit.
      username: Bybitr0Ya1ewiThc
    - nickname: bar
      username: BybitH3eselEbiGM

log:
  enabled: true
  format: text
  output:
    # - $STDERR
    - .tiny-short.log

misc:
  use_color_output: auto

debug:
  enabled: true
  skip_transaction: true # No transfer and no trading.
  skip_transfer: true # No transfer.
