name: Money Printer
run-name: Make some coins 🪙

on:
  workflow_dispatch:
    inputs:
      withLog:
        description: "Enable logs"
        type: boolean
        required: false
        default: false

  schedule:
    - cron: "5 */8 * * *"

jobs:
  Short:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - uses: actions/cache@v4
        with:
          path: .tiny-short.secrets.json.aes
          key: Royale with Cheese

      - name: Decrypt secrets
        run: |
          if [ -f .tiny-short.secrets.json.aes ]; then
            openssl enc -d -aes-256-cbc -salt -pbkdf2 \
              -in .tiny-short.secrets.json.aes \
              -out .tiny-short.secrets.json \
              -k '${{ secrets.STORE_PASSWORD }}' \
            || true
            
            rm .tiny-short.secrets.json.aes
          fi

      - name: Set secrets
        run: |
          echo '${{ secrets.BYBIT_API_KEY        }}' > api.key
          echo '${{ secrets.BYBIT_API_KEY_SECRET }}' > key.pem

      - name: Config
        run: |
          echo '
          secret:
            type: RSA
            api_key_file: api.key
            private_key_file: key.pem

            store:
              enabled: true
              path: .tiny-short.secrets.json

          coins:
            - SOL

          transfer:
            enabled: true
            to:
              nickname: somnus
              username: Bybitplg2HTZRgxP
            from:
              - username: $MAIN
              - nickname: hypnos
                username: BybitydINQ0FotFH
              - nickname: gamer
                username: BybitvPVPcujX3j6

          log:
            enabled: ${{ inputs.withLog && 'true' || 'false' }}
            format: text
            output:
              - $STDERR

          misc:
            use_color_output: always

          ' > .tiny-short.yaml

      - name: Order
        run: go run .

      - name: Encrypt secrets
        run: |
          openssl enc -aes-256-cbc -salt -pbkdf2 \
            -in .tiny-short.secrets.json \
            -out .tiny-short.secrets.json.aes \
            -k "${{ secrets.STORE_PASSWORD }}"
